# Generated by Django 4.1.2 on 2022-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=20)),
                ('taille', models.IntegerField(default=0)),
                ('poids', models.IntegerField(default=0)),
                ('pv', models.IntegerField(default=0)),
                ('attaque', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('special_attaque', models.IntegerField(default=0)),
                ('special_defense', models.IntegerField(default=0)),
                ('front_image', models.URLField()),
                ('back_image', models.URLField()),
            ],
        ),
    ]
