# Generated by Django 4.1.2 on 2022-10-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='back_image',
        ),
    ]
