# Generated by Django 4.1.2 on 2022-10-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0004_type_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='front_image',
            field=models.URLField(blank=True, default=None),
        ),
    ]
