# Generated by Django 4.1.2 on 2022-11-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0005_alter_pokemon_front_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='equipes',
            field=models.ManyToManyField(to='pokedexapp.equipe'),
        ),
    ]
