# Generated by Django 4.1.2 on 2022-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexapp', '0006_equipe_pokemon_equipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='equipes',
        ),
        migrations.AddField(
            model_name='equipe',
            name='pokemons',
            field=models.ManyToManyField(to='pokedexapp.pokemon'),
        ),
    ]
